server:
  port: 8080

spring:
  application:
    name: ProductManagement
  datasource:
    url: jdbc:postgresql://localhost:5432/lingcorp
#    username: gramdhan
#    password: Lili@123
    username: postgres
    password: postgrespass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

user:
  token:
    expiredTime: 60


jwt:
  secret: afd4fb233dbdee52016dc54c049686aafa7c85efca1229392aed424fdb49c09fx88as8gX2NRXgZzrMqBEry
